default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  # Necessary to allow creating a db with different encodings.
  # See http://www.postgresql.org/docs/9.1/static/manage-ag-templatedbs.html for details
  template: template0

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] %>
