version: '3.7'

volumes:
  transition-tmp:

x-transition: &transition
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: transition
  platform: linux/amd64
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - transition-tmp:/govuk/transition/tmp
  working_dir: /govuk/transition

services:
  transition-lite:
    <<: *transition
    depends_on:
      # The version of PostgreSQL temporarily does not match production, as an upgrade in production is being worked on (tracked in https://trello.com/c/9PayaOSK)
      - postgres-13
      - redis
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      DATABASE_URL: "postgresql://postgres@postgres-13/transition"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/transition-test"
      REDIS_URL: redis://redis

  transition-app: &transition-app
    <<: *transition
    depends_on:
      - nginx-proxy
      - postgres-13
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/transition"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: transition.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
