version: '3.7'

volumes:
  router-api-tmp:

x-router-api: &router-api
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: router-api
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - router-api-tmp:/govuk/router-api/tmp
  working_dir: /govuk/router-api

services:
  router-api-lite:
    <<: *router-api
    depends_on:
      - mongo-3.6
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/router"
      TEST_MONGODB_URI: "mongodb://mongo-3.6/router-test"

  router-api-app: &router-api-app
    <<: *router-api
    depends_on:
      - mongo-3.6
      - router-app
      - nginx-proxy
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/router"
      VIRTUAL_HOST: router-api.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
