version: '3.7'

x-govuk-content-schemas: &govuk-content-schemas
  build:
    context: .
    dockerfile: Dockerfile
  image: govuk-content-schemas
  volumes:
    - ..:/govuk:delegated
    - rbenv-versions:/rbenv/versions
    - rbenv-shims:/rbenv/shims
    - home:/home/build
  working_dir: /govuk/govuk-content-schemas

services:
  govuk-content-schemas-lite:
    <<: *govuk-content-schemas
