govuk-content-schemas: $(GOVUK_ROOT_DIR)/govuk-content-schemas
	$(COMPOSE_RUN) govuk-content-schemas rbenv install -s && gem install --conservative bundler
	$(COMPOSE_RUN) govuk-content-schemas-lite bundle
