version: '3.7'

x-router: &router
  build:
    context: .
    dockerfile: projects/router/Dockerfile
  image: router
  volumes:
    - go:/go
    - ${GOVUK_ROOT_DIR:-~/govuk}/router:/go/src/github.com/alphagov/router:delegated
    - root-home:/root
  working_dir: /go/src/github.com/alphagov/router

services:
  router-lite:
    <<: *router
    depends_on:
      - mongo-3.6
    environment:
      BINARY: /go/src/github.com/alphagov/router/router
      DEBUG: "true"
      ROUTER_MONGO_URL: mongo-3.6
      ROUTER_MONGO_DB: router

  router-app: &router-app
    <<: *router
    depends_on:
      - mongo-3.6
      - nginx-proxy
    expose:
      - "8080"
      - "3055"
    environment:
      VIRTUAL_HOST: router.dev.gov.uk,www.dev.gov.uk,www-origin.dev.gov.uk
      VIRTUAL_PORT: 8080
      ROUTER_MONGO_URL: mongo-3.6
      ROUTER_MONGO_DB: router
      ROUTER_APIADDR: :3055
      ROUTER_BACKEND_HEADER_TIMEOUT: 60s
    command: ./router

  router-app-draft:
    <<: *router-app
    environment:
      VIRTUAL_HOST: draft-router.dev.gov.uk,draft-origin.dev.gov.uk
      VIRTUAL_PORT: 8080
      ROUTER_MONGO_URL: mongo-3.6
      ROUTER_MONGO_DB: draft-router
      ROUTER_APIADDR: :3055
      ROUTER_BACKEND_HEADER_TIMEOUT: 60s
