govuk_publishing_components: $(GOVUK_ROOT_DIR)/govuk_publishing_components
	$(COMPOSE_RUN) govuk_publishing_components-lite install -s && gem install --conservative bundler
	$(COMPOSE_RUN) govuk_publishing_components-lite bundle
