version: '3.7'

volumes:
  govuk-content-schemas-tmp:

x-govuk-content-schemas: &govuk-content-schemas
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-content-schemas
  platform: linux/amd64
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - govuk-content-schemas-tmp:/govuk/govuk-content-schemas/tmp
  working_dir: /govuk/govuk-content-schemas

services:
  govuk-content-schemas-lite:
    <<: *govuk-content-schemas

  govuk-content-schemas-app:
    <<: *govuk-content-schemas
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: govuk-content-schemas.dev.gov.uk
    expose:
      - "4567"
    command: bundle exec ruby app.rb
