volumes:
  frontend-tmp:
  frontend-node-modules:

x-frontend: &frontend
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  depends_on:
    - account-api-app
    - content-store-app
    - nginx-proxy
    - publishing-api-app
    - router-app
    - search-api-app
  image: frontend
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - frontend-tmp:/govuk/frontend/tmp
    - frontend-node-modules:/govuk/frontend/node_modules
  working_dir: /govuk/frontend

services:
  frontend-lite:
    <<: *frontend

  frontend-app: &frontend-app
    <<: *frontend
    environment:
      ALLOW_LOCAL_CONTENT_ITEM_OVERRIDE: "true"
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: http://content-store.dev.gov.uk
      VIRTUAL_HOST: frontend.dev.gov.uk
      VIRTUAL_PORT: 3005
      BINDING: 0.0.0.0
      WEB_CONCURRENCY: 0
    ports:
      - "12345:12345"
    expose:
      - "3005"
    command: bin/dev

  frontend-app-live:
    <<: *frontend
    depends_on:
      - account-api-app-live
      - nginx-proxy
    environment:
      ALLOW_LOCAL_CONTENT_ITEM_OVERRIDE: "true"
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_SEARCH_API_URI: https://www.gov.uk/api
      VIRTUAL_HOST: frontend.dev.gov.uk
      VIRTUAL_PORT: 3005
      BINDING: 0.0.0.0
      WEB_CONCURRENCY: 0
    expose:
      - "3005"
    command: bin/dev

  frontend-app-integration:
    <<: *frontend
    depends_on:
      - account-api-app-live
      - nginx-proxy
    environment:
      ALLOW_LOCAL_CONTENT_ITEM_OVERRIDE: "true"
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      #ASSET_MANAGER_BEARER_TOKEN: <get an asset manager token from https://signon.integration.publishing.service.gov.uk/api_users>
      PLEK_SERVICE_ASSET_MANAGER_URI: https://assets-origin.eks.integration.govuk.digital
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.integration.publishing.service.gov.uk/api
      PLEK_SERVICE_SEARCH_API_URI: https://www.integration.publishing.service.gov.uk/api
      PLEK_SERVICE_PUBLISHING_API_URI: http://host.docker.internal:8080 # Requires `kubectl port-forward -n apps deploy/publishing-api 8080:8080`
      VIRTUAL_HOST: frontend.dev.gov.uk
      VIRTUAL_PORT: 3005
      BINDING: 0.0.0.0
      WEB_CONCURRENCY: 0
    expose:
      - "3005"
    command: bin/dev

  frontend-app-draft:
    <<: *frontend
    depends_on:
      - account-api-app
      - content-store-app-draft
      - nginx-proxy
      - publishing-api-app
      - router-app
      - search-api-app
    environment:
      GOVUK_RAILS_JSON_LOGGING: "false"
      ALLOW_LOCAL_CONTENT_ITEM_OVERRIDE: "true"
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: http://draft-content-store.dev.gov.uk
      VIRTUAL_HOST: draft-frontend.dev.gov.uk
      VIRTUAL_PORT: 3005
      BINDING: 0.0.0.0
      WEB_CONCURRENCY: 0
      PIDFILE: ./tmp/pids/server-draft.pid
      RAILS_DEVELOPMENT_HOSTS: draft-frontend.dev.gov.uk
    expose:
      - "3005"
    command: bin/dev
