version: '3.7'

x-govuk_app_config: &govuk_app_config
  build:
    context: .
    dockerfile: Dockerfile
  image: govuk_app_config
  volumes:
    - ..:/govuk:delegated
    - rbenv-versions:/rbenv/versions
    - rbenv-shims:/rbenv/shims
    - home:/home/build
  working_dir: /govuk/govuk_app_config

services:
  govuk_app_config-lite:
    <<: *govuk_app_config
