version: '3.7'

volumes:
  contacts-admin-tmp:
  contacts-admin-node-modules:

x-contacts-admin: &contacts-admin
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: contacts-admin
  platform: linux/amd64
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - contacts-admin-tmp:/govuk/contacts-admin/tmp
    - contacts-admin-node-modules:/govuk/contacts-admin/node_modules
  working_dir: /govuk/contacts-admin

services:
  contacts-admin-lite:
    <<: *contacts-admin
    depends_on:
      - mysql-8
      - redis
    environment:
      DATABASE_URL: "mysql2://root:root@mysql-8/contacts_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql-8/contacts_test"
      REDIS_URL: redis://redis

  contacts-admin-app: &contacts-admin-app
    <<: *contacts-admin
    depends_on:
      - mysql-8
      - redis
      - publishing-api-app
      - nginx-proxy
      - content-store-app
      - whitehall-app
    environment:
      DATABASE_URL: "mysql2://root:root@mysql-8/contacts_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql-8/contacts_test"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: contacts-admin.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
