version: '3.7'

volumes:
  publisher-tmp:
  publisher-node-modules:

x-publisher: &publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: publisher
  platform: linux/amd64
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - publisher-tmp:/govuk/publisher/tmp
    - publisher-node-modules:/govuk/publisher/node_modules
  working_dir: /govuk/publisher

services:
  publisher-lite:
    <<: *publisher
    depends_on:
      - redis
      - mongo-3.6
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/publisher"
      TEST_MONGODB_URI: "mongodb://mongo-3.6/publisher-test"
      REDIS_URL: redis://redis

  publisher-app: &publisher-app
    <<: *publisher
    depends_on:
      - redis
      - mongo-3.6
      - nginx-proxy
      - publishing-api-app
      - link-checker-api-app
      - publisher-worker
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: publisher.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  publisher-worker:
    <<: *publisher
    depends_on:
      - redis
      - mongo-3.6
      - nginx-proxy
      - publishing-api-app
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
