x-search-api-v2: &search-api-v2
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: search-api-v2
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - search-api-v2-tmp:/govuk/search-api-v2/tmp
    - root-home:/root
    # Mount the host's gcloud config directory into the container so that the app can use
    # Application Default Credentials (required to use Discovery Engine locally)
    - "~/.config/gcloud:/root/.config/gcloud:delegated"
  working_dir: /govuk/search-api-v2

volumes:
  search-api-v2-tmp:

services:
  search-api-v2-lite:
    <<: *search-api-v2
    depends_on:
      - rabbitmq
      - search-api-v2-redis
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      REDIS_URL: redis://search-api-v2-redis
      PUBLISHED_DOCUMENTS_MESSAGE_QUEUE_NAME: search_api_v2_published_documents
      GOOGLE_CLOUD_PROJECT_ID: none
      DISCOVERY_ENGINE_DEFAULT_COLLECTION_NAME: none
      DISCOVERY_ENGINE_DEFAULT_LOCATION_NAME: none

  search-api-v2-app:
    <<: *search-api-v2
    depends_on:
      - nginx-proxy
      - rabbitmq
      - search-api-v2-redis
      - search-api-v2-document-sync-worker
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq"
      REDIS_URL: redis://search-api-v2-redis
      PUBLISHED_DOCUMENTS_MESSAGE_QUEUE_NAME: "search_api_v2_published_documents"
      RAILS_DEVELOPMENT_HOSTS: "search-api-v2.dev.gov.uk,search-api-v2-app"
      VIRTUAL_HOST: "search-api-v2.dev.gov.uk"
      BINDING: "0.0.0.0"
      GOOGLE_CLOUD_PROJECT_ID: "780375417592"
      DISCOVERY_ENGINE_DEFAULT_COLLECTION_NAME: "projects/780375417592/locations/global/collections/default_collection"
      DISCOVERY_ENGINE_DEFAULT_LOCATION_NAME: "projects/780375417592/locations/global"
    expose:
      - "3000"
    command: bin/rails server --restart

  search-api-v2-document-sync-worker:
    <<: *search-api-v2
    depends_on:
      - rabbitmq
      - search-api-v2-redis
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq"
      REDIS_URL: redis://search-api-v2-redis
      PUBLISHED_DOCUMENTS_MESSAGE_QUEUE_NAME: "search_api_v2_published_documents"
      GOOGLE_CLOUD_PROJECT_ID: "780375417592"
      DISCOVERY_ENGINE_DEFAULT_COLLECTION_NAME: "projects/780375417592/locations/global/collections/default_collection"
      DISCOVERY_ENGINE_DEFAULT_LOCATION_NAME: "projects/780375417592/locations/global"
    command: bin/rake document_sync_worker:run

  search-api-v2-redis:
    image: redis
