#!/usr/bin/env bash

# **************************************************************
# DO NOT ADD NEW STUFF IN HERE
#
# This is meant to be a simple wrapper script to pass some '-f'
# flags to docker-compose. Its behaviour should not depend on
# its arguments. We do not want our own bespoke CLI, as this can
# only lead to complexity, performance and maintenance overheads
# on top of docker and docker-compose.
# **************************************************************

COMPOSE_FLAGS=("-f" "$(dirname "$0")/../docker-compose.yml")
COMPOSE_FILES="$(dirname "$0")/../projects/*/docker-compose.yml"
GOVUK_DOCKER_CONTAINER_RUNTIME="${GOVUK_DOCKER_CONTAINER_RUNTIME:-docker}"

for file in $COMPOSE_FILES; do
  COMPOSE_FLAGS+=("-f" "$file")
done

if ! "$(dirname "$0")"/govuk-docker-version >/dev/null; then
  read -rp "Press enter to continue..."
fi

>&2 echo "${GOVUK_DOCKER_CONTAINER_RUNTIME} compose -f [...] $*"
${GOVUK_DOCKER_CONTAINER_RUNTIME} compose "${COMPOSE_FLAGS[@]}" "$@"
