version: '3.7'

x-cache-clearing-service: &cache-clearing-service
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: cache-clearing-service
  platform: linux/amd64
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/cache-clearing-service

services:
  cache-clearing-service-lite:
    <<: *cache-clearing-service
