volumes:
  places-manager-tmp:

x-places-manager: &places-manager
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: places-manager
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - places-manager-tmp:/govuk/places-manager/tmp
  working_dir: /govuk/places-manager

services:
  places-manager-lite:
    <<: *places-manager
    depends_on:
      - postgres-18-postgis
      - places-manager-redis
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-18-postgis/places-manager"
      TEST_DATABASE_URL: "postgis://postgres:password@postgres-18-postgis/places-manager-test"
      REDIS_URL: redis://places-manager-redis

  places-manager-app: &places-manager-app
    <<: *places-manager
    depends_on:
      - postgres-18-postgis
      - local-links-manager-app
      - locations-api-app
      - nginx-proxy
      - places-manager-redis
      - places-manager-worker
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-18-postgis/places-manager"
      VIRTUAL_HOST: places-manager.dev.gov.uk
      VIRTUAL_PORT: 3000
      BINDING: 0.0.0.0
      REDIS_URL: redis://places-manager-redis
      WEB_CONCURRENCY: 0
    expose:
      - "3000"
    command: bin/rails s --restart
    ports:
      - "12349:12345"

  places-manager-app-ports: &places-manager-app
    <<: *places-manager
    depends_on:
      - postgres-18-postgis
      - nginx-proxy
      - places-manager-redis
      - places-manager-worker-ports
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-18-postgis/places-manager"
      PLEK_SERVICE_CONTENT_STORE_URI: http://content-store:8080
      PLEK_SERVICE_LOCATIONS_API_URI: http://locations-api:8081
      PLEK_SERVICE_SEARCH_API_URI: http://search-api:8082
      VIRTUAL_HOST: places-manager.dev.gov.uk
      VIRTUAL_PORT: 3000
      BINDING: 0.0.0.0
      REDIS_URL: redis://places-manager-redis
      WEB_CONCURRENCY: 0
    expose:
      - "3000"
    command: bin/rails s --restart
    ports:
      - "12349:12345"
    extra_hosts:
      "content-store": host-gateway
      "locations-api": host-gateway
      "search-api": host-gateway

  places-manager-worker-ports:
    <<: *places-manager
    depends_on:
      - postgres-18-postgis
      - nginx-proxy
      - places-manager-redis
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-18-postgis/places-manager"
      PLEK_SERVICE_CONTENT_STORE_URI: http://content-store:8080
      PLEK_SERVICE_LOCATIONS_API_URI: http://locations-api:8081
      PLEK_SERVICE_SEARCH_API_URI: http://search-api:8082
      REDIS_URL: redis://places-manager-redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    extra_hosts:
      "content-store": host-gateway
      "locations-api": host-gateway
      "search-api": host-gateway

  places-manager-worker:
    <<: *places-manager
    depends_on:
      - postgres-18-postgis
      - local-links-manager-app
      - locations-api-app
      - nginx-proxy
      - places-manager-redis
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-18-postgis/places-manager"
      REDIS_URL: redis://places-manager-redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml

  places-manager-redis:
    image: redis