volumes:
  places-manager-tmp:

x-places-manager: &places-manager
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: places-manager
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - places-manager-tmp:/govuk/places-manager/tmp
  working_dir: /govuk/places-manager

services:
  places-manager-lite:
    <<: *places-manager
    depends_on:
      - postgres-14-postgis
      - places-manager-redis
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-14-postgis/places-manager"
      TEST_DATABASE_URL: "postgis://postgres:password@postgres-14-postgis/places-manager-test"
      REDIS_URL: redis://places-manager-redis

  places-manager-app: &places-manager-app
    <<: *places-manager
    depends_on:
      - postgres-14-postgis
      - local-links-manager-app
      - locations-api-app
      - nginx-proxy
      - places-manager-redis
      - places-manager-worker
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-14-postgis/places-manager"
      VIRTUAL_HOST: places-manager.dev.gov.uk
      BINDING: 0.0.0.0
      REDIS_URL: redis://places-manager-redis
    expose:
      - "3000"
    command: bin/rails s --restart

  places-manager-worker:
    <<: *places-manager
    depends_on:
      - postgres-14-postgis
      - local-links-manager-app
      - locations-api-app
      - nginx-proxy
      - places-manager-redis
    environment:
      DATABASE_URL: "postgis://postgres:password@postgres-14-postgis/places-manager"
      REDIS_URL: redis://places-manager-redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml

  places-manager-redis:
    image: redis