version: '3.7'

x-govuk-lint: &govuk-lint
  build:
    context: .
    dockerfile: Dockerfile
  image: govuk-lint
  volumes:
    - ..:/govuk:delegated
    - rbenv-versions:/rbenv/versions
    - rbenv-shims:/rbenv/shims
    - home:/home/build
  working_dir: /govuk/govuk-lint

services:
  govuk-lint-lite:
    <<: *govuk-lint
